# Site settings
title: HenrÃ© Botha
email: ***REMOVED***
description: > # this means to ignore newlines until "baseurl:"
  Learning while doing. A blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://henrebotha.github.io" # the base hostname & protocol for your site
twitter_username: henrebotha
github_username:  henrebotha

# Build settings
markdown: redcarpet
highlighter: pygments
